### ISSUE TITLE
Disabling controller input

### ISSUE THREAD

**Issue by walkerreynolds16** [ITVlab/YouTube-Tv-Player#1]
I found your repo and it works really well for what I need in my app, but i was wondering if you ever implemented a way to disable controller input to the player. Right now, the only buttons that do anything are the directional buttons on my remote, but I want them to be disabled. If you haven't implemented a way to do this, do you have any recommendations on how to implement it? 

Thanks

**Comment by Fleker** [comment]
You could, in your activity, override the `onKeyDown` method and not pass on commands, so just returning `true`.

**Comment by walkerreynolds16** [comment]
My onKeyDown and onKeyUp functions are not capturing the controller input right now which leads to the video skipping 5 seconds. I'll see if something else is wrong with my code.

**Comment by walkerreynolds16** [comment]
Well my onKeyDown and onKeyUp functions are only capturing the back and menu button presses and nothing else so pressing the navigate button still skip the video. Any ideas why this is happening?

**Comment by Fleker** [comment]
I think for controller inputs you'd need to look at generic motion: https://developer.android.com/training/game-controllers/controller-input.html

**Comment by walkerreynolds16** [comment]
I think I got it working late yesterday after a break. I started using onDispatchKeyEvent which was able to detect all key presses. I was also able to stop the skipping of the player using this function.

Thanks for the help

**Comment by walkerreynolds16** [comment]
I think I got it working late yesterday after a break. I started using onDispatchKeyEvent which was able to detect all key presses. I was also able to stop the skipping of the player using this function.

Thanks for the help
